# Generated by Django 3.2.9 on 2023-03-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yaratilma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
